sudo : required
services : 
  - docker
before_install:
  - docker build -t laridev/react-redux-itbook -f Dockerfile.dev .  

scripts :
  - docker run laridev/react-redux-itbook npm run test -- --coverage