export const FETCH_BOOKS = 'FETCH_BOOKS';

export const FETCH_BOOKS_WITH_PAGE = 'FETCH_BOOKS_WITH_PAGE';

export const ADD_SEARCH_TEXT = 'ADD_SEARCH_TEXT';

export const GET_BOOK_INFO = 'GET_BOOK_INFO';


 
